name: Check External Links

on:
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run lychee-action on .qmd files
      id: lychee
      uses: lycheeverse/lychee-action@v1
      with:
        args: "'**/*.qmd' --exclude doi.org --exclude data.4tu.nl --exclude isbn.org --exclude github.com/ubvu/open-handbook"
        format: markdown
        jobSummary: true
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ./lychee/out.md
